baseURL = "https://adrienbabet.com/"
languageCode = "en-us"
title = "Babet's Site"
theme = "hextra"

[module]
ignoreFiles = ["themes/hextra/static/*"]

[params.navbar]
displayTitle = true
displayLogo = false

[[menu.main]]
name = "Projects"
pageRef = "/projects"
weight = 1

[[menu.main]]
name = "Contact"
pageRef = "/contact"
weight = 2

[[menu.main]]
name = "Search"
weight = 3
[menu.main.params]
type = "search"
