baseURL = "https://adrienbabet.com/"
languageCode = "en-us"
title = "Babet's Site"
theme = "hextra"

[module]
ignoreFiles = ["themes/hextra/static/*"]

[params.navbar]
displayTitle = true
displayLogo = true

[params.navbar.logo]
path = "images/Calligraphy-B.png"
link = "/"
width = 40
height = 20


[[menu.main]]
name = "Projects"
pageRef = "/projects"
weight = 1

[[menu.main]]
name = "Search"
weight = 3
[menu.main.params]
type = "search"
