baseURL = "https://adrienbabet.com/"
languageCode = "en-us"
title = "Babet's Site"
theme = "hextra"

[module]
ignoreFiles = ["themes/hextra/static/*"]

[params]
  [params.navbar]
    displayTitle = true
    displayLogo = true

    [params.navbar.logo]
      path = "custom-favicon.svg"
      dark = "custom-favicon-dark.svg"
      link = "/"
      width = 40


[[menu.main]]
identifier = "projects"
name = "Projects"
pageRef = "/projects"
weight = 1

[[menu.main]]
name = "Contact"
pageRef = "/contact"
weight = 2

[[menu.main]]
name = "Search"
weight = 3
[menu.main.params]
type = "search"

[[menu.main]]
name = "CV"
pageRef = "/cv"
weight = 4

defaultContentLanguage = "en"

[languages]
  [languages.en]
    languageName = "English"
    weight = 1

  [languages.fr]
    languageName = "Français"
    weight = 2
